### ISSUE TITLE
User Guide Improvement/Addition to the README.md

### ISSUE THREAD

**Issue by Charan2k** [tanmaypradhan4112/Alien-Invasion#11]
First things first, it would be better if you can provide how to install/run/start the application/game.
Ideally it should be in the user guide section of the [README.md](https://github.com/tanmaypradhan4112/Alien-Invasion/blob/main/README.md)

It's really tough for a non python background guy to use this.

**Comment by tanmaypradhan4112** [comment]
I didn't know about that. Will do that

**Comment by Charan2k** [comment]
I might help it getting done, soon as I get to kick start the project up and running properly

**Comment by Charan2k** [comment]
@tanmaypradhan4112  
Please check the PR: #12 and you may close this issue or let me know if there's anything else
